version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: walkthrough-5-postgres
    environment:
      POSTGRES_DB: walkthrough-5
      POSTGRES_USER: jaimes
      POSTGRES_PASSWORD: jaimesjames
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: walkthrough-5-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: